// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSession(arg1:string):Promise<main.GameSession>;

export function RegisterGamePack(arg1:string,arg2:Record<string, string>):Promise<void>;

export function StartGame(arg1:string):Promise<main.GameTurnResult>;

export function SubmitChoice(arg1:string,arg2:string):Promise<main.GameTurnResult>;
