// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function RegisterGamePack(arg1, arg2) {
  return window['go']['main']['App']['RegisterGamePack'](arg1, arg2);
}

export function StartGame(arg1) {
  return window['go']['main']['App']['StartGame'](arg1);
}

export function SubmitChoice(arg1, arg2) {
  return window['go']['main']['App']['SubmitChoice'](arg1, arg2);
}
