// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appconf} from '../models';
import {roleplay} from '../models';

export function GetAppConfig():Promise<appconf.AppConfig>;

export function GetSession(arg1:string):Promise<roleplay.GameSession>;

export function RegisterGamePack(arg1:string,arg2:Record<string, string>):Promise<void>;

export function StartGame(arg1:string):Promise<roleplay.GameTurnResult>;

export function SubmitChoice(arg1:string,arg2:string):Promise<roleplay.GameTurnResult>;

export function UpdateAppConfig(arg1:appconf.AppConfig):Promise<void>;
