// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGame(arg1) {
  return window['go']['main']['App']['CreateGame'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function ImportGamePack(arg1) {
  return window['go']['main']['App']['ImportGamePack'](arg1);
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function ListUnlockedAchievements(arg1) {
  return window['go']['main']['App']['ListUnlockedAchievements'](arg1);
}

export function RegisterGamePack(arg1, arg2) {
  return window['go']['main']['App']['RegisterGamePack'](arg1, arg2);
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function SaveSnapshot(arg1, arg2) {
  return window['go']['main']['App']['SaveSnapshot'](arg1, arg2);
}

export function StartGame(arg1) {
  return window['go']['main']['App']['StartGame'](arg1);
}

export function SubmitChoice(arg1, arg2) {
  return window['go']['main']['App']['SubmitChoice'](arg1, arg2);
}

export function SubmitCustomChoice(arg1, arg2) {
  return window['go']['main']['App']['SubmitCustomChoice'](arg1, arg2);
}

export function UpdateAppConfig(arg1) {
  return window['go']['main']['App']['UpdateAppConfig'](arg1);
}

export function UpdateGame(arg1, arg2) {
  return window['go']['main']['App']['UpdateGame'](arg1, arg2);
}
