// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {roleplay} from '../models';
import {appconf} from '../models';
import {service} from '../models';

export function CreateGame(arg1:roleplay.LibraryGame):Promise<roleplay.LibraryGame>;

export function DeleteGame(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetAppConfig():Promise<appconf.AppConfig>;

export function GetGame(arg1:string):Promise<roleplay.LibraryGame>;

export function GetGames():Promise<Array<roleplay.LibraryGame>>;

export function GetSession(arg1:string):Promise<roleplay.GameSession>;

export function ImportGamePack(arg1:Record<string, string>):Promise<roleplay.ImportGameResult>;

export function ListSessions(arg1:string):Promise<Array<service.SessionSummary>>;

export function RegisterGamePack(arg1:string,arg2:Record<string, string>):Promise<void>;

export function ResumeSession(arg1:string):Promise<roleplay.GameTurnResult>;

export function SaveSnapshot(arg1:string,arg2:string):Promise<service.SessionSummary>;

export function StartGame(arg1:string):Promise<roleplay.GameTurnResult>;

export function SubmitChoice(arg1:string,arg2:string):Promise<roleplay.GameTurnResult>;

export function UpdateAppConfig(arg1:appconf.AppConfig):Promise<void>;

export function UpdateGame(arg1:string,arg2:roleplay.LibraryGame):Promise<roleplay.LibraryGame>;
